#!/usr/bin/env bash
# shellcheck shell=bash
# WSL/Linux launch configuration and optional service startup.

RELOCATE_TARGET="$HOME/director-web"

copy_project_to_ext4() {
  local target="$1"
  mkdir -p "$target"
  info "复制项目到 $target（排除 .git/.venv/node_modules/运行时数据）"
  tar -C "$SCRIPT_DIR" \
    --exclude=.git \
    --exclude=.venv \
    --exclude=node_modules \
    --exclude=data \
    --exclude=.data \
    --exclude=.director-install \
    --exclude=.tools \
    --exclude=ComfyUI \
    --exclude=frontend/node_modules \
    --exclude=frontend/dist \
    -cf - . | tar -C "$target" -xf - || {
    error "项目复制失败"
    return 1
  }
  ok "项目已复制到 $target"
}

step_resolve_layout() {
  [[ "$PROJECT_ON_WINDOWS_FS" == true ]] || {
    ok "项目位于 Linux 文件系统，布局无需调整"
    return 0
  }

  local relocate=false
  if [[ "${DIRECTOR_SKIP_RELOCATION:-false}" == true ]]; then
    warn "已跳过 WSL 项目迁移"
    return 0
  fi

  if [[ -f "$RELOCATE_TARGET/bootstrap.sh" ]]; then
    ask_yes_no "检测到 $RELOCATE_TARGET，是否直接切换到该目录继续安装？" y && relocate=true
  else
    ask_yes_no "当前项目位于 /mnt/c，是否自动复制到 $RELOCATE_TARGET 并从新目录继续？" y && relocate=true
  fi

  if [[ "$relocate" != true ]]; then
    warn "继续在当前 Windows 文件系统安装；SQLite/WAL、flock 和 npm 性能可能异常"
    return 0
  fi

  if [[ ! -f "$RELOCATE_TARGET/bootstrap.sh" ]]; then
    copy_project_to_ext4 "$RELOCATE_TARGET" || return 1
  fi
  info "切换到 $RELOCATE_TARGET 并重新执行 bootstrap"
  release_lock
  exec bash "$RELOCATE_TARGET/bootstrap.sh" "${ORIGINAL_ARGS[@]}"
}

launcher_mode() {
  if [[ "$IS_WSL" == true || "$HAS_USER_SYSTEMD" != true ]]; then
    printf 'supervisor\n'
  else
    printf 'systemd\n'
  fi
}

default_listen_host() {
  if [[ "$IS_WSL" == true ]]; then
    printf '0.0.0.0\n'
  else
    printf '127.0.0.1\n'
  fi
}

write_env_file() {
  local listen_host="$1" mode="$2" tmpdir
  if [[ "$IS_WSL" == true ]]; then
    tmpdir="$SCRIPT_DIR/.tmp"
  else
    tmpdir="${DIRECTOR_TMPDIR:-}"
  fi
  mkdir -p "$STATE_DIR"
  {
    printf '# Generated by bootstrap.sh. Source this file from director.sh or your shell.\n'
    printf 'export DIRECTOR_HOST=%q\n' "$listen_host"
    printf 'export DIRECTOR_PORT=%q\n' "${DIRECTOR_BACKEND_PORT:-8787}"
    printf 'export DIRECTOR_FRONTEND_HOST=%q\n' "$listen_host"
    printf 'export DIRECTOR_FRONTEND_PORT=%q\n' "${DIRECTOR_FRONTEND_PORT:-4173}"
    printf 'export DIRECTOR_API_ORIGIN=%q\n' "http://127.0.0.1:${DIRECTOR_BACKEND_PORT:-8787}"
    printf 'export DIRECTOR_NODE_BIN_DIR=%q\n' "${NODE_BIN_DIR:-}"
    printf 'export DIRECTOR_COMFYUI_ROOT=%q\n' "${COMFYUI_ROOT:-}"
    printf 'export DIRECTOR_COMFYUI_PORT=%q\n' "$COMFYUI_PORT"
    printf 'export DIRECTOR_COMFYUI_LISTEN=%q\n' "$COMFYUI_LISTEN"
    printf 'export DIRECTOR_COMFYUI_URL=%q\n' "${COMFYUI_URL:-}"
    printf 'export DIRECTOR_FORCE_SUPERVISOR=%q\n' "$([[ "$mode" == supervisor ]] && printf true || printf false)"
    [[ -n "$tmpdir" ]] && printf 'export DIRECTOR_TMPDIR=%q\n' "$tmpdir"
  } >"$ENV_FILE"
  ok "启动配置已写入 $ENV_FILE"
}

step_configure_launcher() {
  local host="${DIRECTOR_BIND_HOST:-$(default_listen_host)}"
  local mode
  mode="$(launcher_mode)"

  if [[ "$IS_WSL" == true && "$host" == 0.0.0.0 ]]; then
    warn "Director 无登录鉴权；WSL2 默认监听 0.0.0.0 以便 Windows localhost 访问。请勿在公共网络暴露。"
  fi

  write_env_file "$host" "$mode"

  if [[ "$mode" == supervisor ]]; then
    ok "启动模式：内置 supervisor（不依赖 systemd）"
  else
    ok "启动模式：systemd user units"
  fi
  ok "Director 监听：$host:${DIRECTOR_BACKEND_PORT:-8787}（前端 ${DIRECTOR_FRONTEND_PORT:-4173}）"
  [[ "$COMFYUI_MODE" != skip ]] && ok "ComfyUI：http://${COMFYUI_LISTEN}:${COMFYUI_PORT}"
  return 0
}

start_comfyui_if_requested() {
  [[ "$COMFYUI_MODE" == skip ]] && return 0
  if [[ "${START_COMFYUI_AFTER_INSTALL:-false}" != true ]]; then
    [[ "$ASSUME_YES" == true ]] && { info "未指定 --start-comfyui，跳过 ComfyUI 启动"; return 0; }
    ask_yes_no "是否现在启动本地 ComfyUI？" y || return 0
  fi
  info "启动 ComfyUI：$COMFYUI_ROOT"
  "$SCRIPT_DIR/.venv/bin/python" "$SCRIPT_DIR/tools/director_supervisor.py" start-comfyui || {
    error "ComfyUI 启动失败，请查看 data/comfyui.log"
    return 1
  }
  ok "ComfyUI 启动命令已提交"
  return 0
}

start_director_if_requested() {
  if [[ "${START_AFTER_INSTALL:-false}" != true ]]; then
    [[ "$ASSUME_YES" == true ]] && { info "未指定 --start，跳过 Director 启动"; return 0; }
    ask_yes_no "是否现在启动 Director 前后端？" y || return 0
  fi
  info "启动 Director"
  "$SCRIPT_DIR/director.sh" start || {
    error "Director 启动失败，请查看 data/director-backend.log 与 data/director-frontend.log"
    return 1
  }
  ok "Director 已启动"
  if [[ "$IS_WSL" == true ]]; then
    info "Windows 浏览器建议访问：http://localhost:${DIRECTOR_FRONTEND_PORT:-4173}"
  else
    info "浏览器访问：http://127.0.0.1:${DIRECTOR_FRONTEND_PORT:-4173}"
  fi
  [[ "$COMFYUI_MODE" != skip ]] && info "请在系统设置中填写 ComfyUI 地址：http://${COMFYUI_LISTEN}:${COMFYUI_PORT}"
  [[ "$COMFYUI_MODE" == skip ]] && info "请在系统设置中填写远程 ComfyUI 地址：$COMFYUI_URL"
  return 0
}

step_start_services_optional() {
  start_comfyui_if_requested || return 1
  start_director_if_requested || return 1
  return 0
}

load_env_file() {
  [[ -f "$ENV_FILE" ]] || return 0
  # shellcheck disable=SC1090
  source "$ENV_FILE"
}
